### ISSUE TITLE
Run in Background

### ISSUE THREAD

**Issue by residuum** [SensorApps/Sensors2OSC#11]
When a user sets "send data" to on, then the app should be able to run in the background.

When the app is sending data , then a notification should be visible in the notification bar.

When the user touches the notification, the app should open.

**Comment by deflost** [comment]
hello, we would like to use this super cool little app in teathre, maybe for a dance show to trigger sounds and visuals.
but only when we are able to look the device so the app have to run in backround, it would be possible!!!
it would be great you can bring this feature inside your app.
r.

**Comment by meta-meta** [comment]
It would be great if it could run while screen is off as well. https://stackoverflow.com/questions/11978742/how-to-keep-an-activity-running-while-screen-off

**Comment by ninjaihero** [comment]
I have let somebody to do it.

**Comment by ricardoscholz** [comment]
we have the same idea of @deflost, for usage in theatre. i have made some tests already for DMX lighting control with marine (www.ricardoscholz.com/marinefr). it works great. but making sure it would keep sending data with the screen off and locked is a must for live usage, actually. thanx for this amazing app! i'm looking forward for this feature! :)
