### ISSUE TITLE
Enable rotation

### ISSUE THREAD

**Issue by residuum** [SensorApps/Sensors2OSC#12]
The app should be rotatable.

**Comment by residuum** [comment]
I have added this in https://github.com/SensorApps/Sensors2OSC/commit/a317b42bd336f104a58c75f30243f9095ea55d51

**Comment by deusanyjunior** [comment]
the rotation is really good. the name Game Rotation Vector (uncalibrated) was too long that covered the OSC label, and the rotation helps to see the label. great *enhancement*!
