### ISSUE TITLE
Most sensors listed twice

### ISSUE THREAD

**Issue by mxa** [SensorApps/Sensors2OSC#17]
It appears as all sensors are listed twice with Sensors2OSC 0.2.0. See screenshots and note the faint scrollbar position on the right.

![photo_2017-07-12_18-14-46](https://user-images.githubusercontent.com/1220707/28127792-0634293c-672e-11e7-8414-33e2c9b2b914.jpg)
![photo_2017-07-12_18-13-28](https://user-images.githubusercontent.com/1220707/28127796-07265c48-672e-11e7-9ba4-e4ad60963ab6.jpg)

**Comment by residuum** [comment]
It looks like only some sensors are reported twice. Do they appear twice in the help screen as well?

What is your device and Android version?

**Comment by mxa** [comment]
Here is the complete list.
Phone is a Sony Xperia Z3+. Emphasis mine to show the double listed items.

nfc (only appears when switched on and app is launched afterwards)
acceleration
magneticfield
magneticfielduncalibrated
gyroscope
gyroscopeuncalibrated
proximity
light
pressure
_accelerometer
magneticfield
magneticfielduncalibrated
gyroscope
gyroscopeuncalibrated
proximity
light
pressure_
gravity
linearacceleration
rotationvector
georotationvector
orientation
tiltdetector
_gravity
linearacceleration
rotationvector
georotationvector
orientation_
stepcounter
stepdetector
significantmotion
gamerotationvector
_stepcounter
stepdetector
gamerotationvector_

In the help section it says my phone has 34 available sensors. The ones that are listed twice have the suffix -WAKEUP SECONDARY

**Comment by residuum** [comment]
OK, I have found this and will try to fix that:

> The list of all sensors present on the device is reported by the HAL implementation.
> - There can be several sensors of the same type. For example, two proximity sensors or two accelerometers.
> - The vast majority of applications request only a single sensor of a given type. For example, an application requesting the default accelerometer will get the first accelerometer in the list.
> - Sensors are often defined by wake-up and non-wake-up pairs, both sensors sharing the same type, but differing by their wake-up characteristic.

https://source.android.com/devices/sensors/

**Comment by residuum** [comment]
I have no device with more than one sensor of a type, but it should be fixed now. Can you verify it?

**Comment by mxa** [comment]
I will test this as soon as an update propagates through f-droid, ok?

**Comment by residuum** [comment]
I'd rather have you test it before, as I am unable to test the fix. I will send you a test build.

**Comment by mxa** [comment]
Can confirm that sensors are now listed only once.
