### ISSUE TITLE
/nfc does not send complete NFC UID

### ISSUE THREAD

**Issue by agomes80** [SensorApps/Sensors2OSC#18]
It seems that the OSC messages generated from NFC tags are truncated. 

Only the first digits of the UID of each tag is sent, which prevents differentiating one tag from another.

Would it be possible to send the entire UID of NFC tags as text over OSC?

Thanks in advance, 
Alex Siqueira

**Comment by residuum** [comment]
I do not have a phone with NFC here, but I can see the problem: The OSC dispatcher only sends float values. I will have a look at it, though.

**Comment by residuum** [comment]
@Knob-dev01: Could you verify this fix?

**Comment by agomes80** [comment]
Hi Thomas,

It looks great!

Problem solved.

Appreciated,
