### ISSUE TITLE
Blender python?

### ISSUE THREAD

**Issue by fromEternal** [SensorApps/Sensors2OSC#22]
How can I stream sensor data to blender to control objects like camera or cube? Is there any script available with you?

**Comment by residuum** [comment]
You can use one of several modules for OSC in Python, but I have not used any of it: https://stackoverflow.com/questions/22135511/a-plethora-of-python-osc-modules-which-one-to-use

**Comment by PanderMusubi** [comment]
See also https://github.com/SensorApps/Sensors2OSC/issues/26

**Comment by residuum** [comment]
No more feedback
