### ISSUE TITLE
Support more sensors

### ISSUE THREAD

**Issue by PanderMusubi** [SensorApps/Sensors2OSC#27]
Please support more sensors. The following are from One Plus 5T

![Screenshot_20190828-005020_Sensors2OSC](https://user-images.githubusercontent.com/198964/63847033-43686e80-c98d-11e9-90ed-02996af107cb.png)
![Screenshot_20190828-005029_Sensors2OSC](https://user-images.githubusercontent.com/198964/63847034-44010500-c98d-11e9-92df-ab48e94de895.png)
![Screenshot_20190828-005037_Sensors2OSC](https://user-images.githubusercontent.com/198964/63847035-44010500-c98d-11e9-9163-337c3cc01752.png)
![Screenshot_20190828-005049_Sensors2OSC](https://user-images.githubusercontent.com/198964/63847037-44010500-c98d-11e9-9655-0e897e600d81.png)

**Comment by residuum** [comment]
Those sensors are not in the official [Android sensor list](https://developer.android.com/reference/android/hardware/Sensor#TYPE_ALL), but are device and / or vendor specific. 

You can still send and access their data by the address, although they have no nice name like "/proximity", but "/30".
