### ISSUE TITLE
App does not build

### ISSUE THREAD

**Issue by tkirshboim** [SensorApps/Sensors2OSC#3]
Hello,
I tried to build the app and failed at two points:
1. The Common module is referencing a non existing commit so I couldn't init and update that submodule. I managed to fix it but then-
2. I tried to create a release APK but some lint errors got in the way. With Android Studio I could start the app at this point as a debug APK without any problem. To fix this I disabled aborting on errors when checking release build.

I forked this repository and made the fixes on my fork so it can be merged from there:
https://github.com/tkirshboim/Sensors2OSC

**Comment by residuum** [comment]
The error was introduced with commit 984f7c92cc708c14eac112976d8d464beaa35d0a

**Comment by deusanyjunior** [comment]
merged!

= )
dj

2015-05-20 4:28 GMT-04:00 Thomas Mayer notifications@github.com:

**Comment by residuum** [comment]
The main problem was, that the commit in SensorsApps/Common was not pushed to github.

**Comment by deusanyjunior** [comment]
yeah, I am sorry. it is kinda hard to remember to commit in both
repositories all the time.. specially when I change Common while working
inside of Sensors2OSC.

= |
dj

2015-05-20 17:42 GMT-04:00 Thomas Mayer notifications@github.com:

**Comment by tkirshboim** [comment]
Hello again - the current master branch is again not building. I fixed it and created a pull request
https://github.com/SensorApps/Sensors2OSC/pull/5

I also added a pd example that uses the pd-vanilla `oscparse` object and created a PR for that:
https://github.com/SensorApps/Sensors2OSC/pull/6

Regarding having the Common module as a submodule - you can have a look at a branch on my fork that uses the Common module as an external gradle dependecy - 
https://github.com/tkirshboim/Sensors2OSC/commit/f1da08a274afc7d6028c6805701f66a167400084

This could prevent issues like a broken submodule reference from happening in the future.

**Comment by deusanyjunior** [comment]
cool! it is better to change this! thanks a lot!

= )
dj

2015-12-17 19:14 GMT-02:00 Tal Kirshboim notifications@github.com:

**Comment by tkirshboim** [comment]
Hi @deusanyjunior - I created a pull request for the replacement of the Common submodule with the jitpack dependency so you can have a look and  decide if you'd like to merge it:
https://github.com/SensorApps/Sensors2OSC/pull/7/files

Jitpack is pretty simple to use. You can have a look at their website:
https://jitpack.io/#SensorApps/Common

**Comment by residuum** [comment]
The PR is merged.
