### ISSUE TITLE
Option to send message in bundle

### ISSUE THREAD

**Issue by PanderMusubi** [SensorApps/Sensors2OSC#31]
Please offer an option (probably by default off) which sends the OSC message inside an OSC bundle.

Some software on the receiving side require a message to be in a bundle and do not act on unbundled OSC messages. A single message in a single bundle would fix that.

**Comment by residuum** [comment]
I am unsure, if the implementation is working. On the one hand, this is putting the values in a bundle, on the other hand, none of my tests produce a different output on the receiver side.

**Comment by PanderMusubi** [comment]
It is some software we cannot change that requires a single message in a single bundle... I know, not optimal.

**Comment by residuum** [comment]
> It is some software we cannot change that requires a single message in a single bundle... I know, not optimal.

I have understood that, but I am unsure, if the implementation in master branch is working, both the Pd and Python examples do not detect a difference. Could you test it? If you cannot build it yourself, let me know, and I will send you an APK.

**Comment by PanderMusubi** [comment]
At the moment not working with that part of the software, so I will see when a next version is there when I work on it again. To test it, I need to set up a lot of hardware which costs more than one day.

**Comment by residuum** [comment]
Release with bundling is out, I have tested the OSC messages.
