### ISSUE TITLE
The Y axis rotation(orientation2) data will suddenly jitter

### ISSUE THREAD

**Issue by RayInst** [SensorApps/Sensors2OSC#40]
The Y axis rotation data will suddenly jitter when the phone is stationary. it is normal for other app.
see the green line in the picture
![image](https://user-images.githubusercontent.com/99521832/193976935-0d235916-4baa-4517-b830-b7e479413f94.png)

**Comment by residuum** [comment]
For investigating the issue, could you please provide the following information:

What is your device name and Android version? 
Does the value jitter all the time or only at the start of sending the data?
Do the gravity and magnetic field values jitter as well?

I suspect, that there may be two different things at work here. 

From the documentation `This constant was deprecated in API level 15.
use SensorManager.getOrientation() instead.` (https://developer.android.com/reference/android/hardware/Sensor#TYPE_ORIENTATION)

Sensors2OSC reads all available sensors from the device, and if no native orientation sensor is available, then it uses getOrientation(), as specified in the documentation. For that, it needs both gravity and magnetic field values to compute the rotation matrix. (https://github.com/SensorApps/Sensors2OSC/blob/master/app/src/main/java/org/sensors2/osc/dispatch/OscDispatcher.java#L44)

Maybe your device reports an orientation sensor, and Sensors2OSC uses that values, and the other app uses getOrientation() to compute the values, or the other way round. Therefore I need the information above to pin the issue.

**Comment by residuum** [comment]
I have just tried it with my installation, and it seems that all values are jittering, when I set the sensor rate to game or fastest. What is the other app that you compare Sensors2OSC to, and what sensor rate does this app use?

**Comment by RayInst** [comment]
This happens with all the rate modes I've tested. Other apps I use are Zig Sim, HyperIMU..

**Comment by residuum** [comment]
I have contacted the author of HyperIMU to get some information on how he is getting the values without jittering.

**Comment by residuum** [comment]
I have no answer from the author of HyperIMU, but I have read some articles about using data from other sensor to detect irregularities in detected data via Kalman filters. Another simpler idea would be to use a weighted mean value of the sensor data, which would not involve using other sensors for it, as the first approach is only possible for dependent sensors. 

Whatever approach I will implement in the app, it will be optional, as my personal usage includes violenty shaking the phone to generate spikes, and these filtering methods may smooth and smear the spikes.

**Comment by RayInst** [comment]
The lasted version has fixed this isssue mostly..

**Comment by residuum** [comment]
Hmm, there was nothing done on the measurement side, strange.
