### ISSUE TITLE
Bug - The XY pad is faulty

### ISSUE THREAD

**Issue by RichardJECooke** [SensorApps/Sensors2OSC#42]
I've tried Sensors2osc xy pad, and the Android app OscController's xy pad, with ReaLearn in Reaper. 

And the Sensors2osc xy pad is definitely faulty. It jumps around a lot, and lags terribly while sending to Reaper. OscController meanwhile works perfectly with no lag or stutter.

**Comment by residuum** [comment]
On my test devices the XY pad values are stable, even when using up to 5 fingers. Maybe OSC Controller is using a method to smooth out small variations with the finger, but I cannot confirm, as I do not have the source code for that app available

**Comment by residuum** [comment]
No more feedback
