### ISSUE TITLE
apk-file for version 0.3.0?

### ISSUE THREAD

**Issue by ollekdsv** [SensorApps/Sensors2OSC#47]
I tried to build an apk-file with version 0.3.0 for an old phone but it fails.
Does anyone know where I can download an old apk-file with version 0.3.0?

/(:-)lle

**Comment by residuum** [comment]
My last device with an installed 0.3.0 died 6 month ago, so I could not download the apk from the phone.

I am currently trying to get a 0.3.0 build working.

**Comment by residuum** [comment]
Here you go: http://sensors2.org/Sensors2OSC-0.3.0-debug.apk
Untested and a debug build, but at least an APK file.

**Comment by ollekdsv** [comment]
Many thanks!
I will test it during the week.
