### ISSUE TITLE
What's the exact sampling rate of the "fastest" sensor rate?

### ISSUE THREAD

**Issue by vYLQs6** [SensorApps/Sensors2OSC#49]
Hi there,

I'm really impressed with Sensors2OSC and its potential for real-time applications.

I'm curious about the exact sampling rate of the **"Fastest"** sensor rate(of **Gyro**) in Sensors2OSC's settings. Is it higher than the 200Hz (5ms) offered by HyperIMU?

I've tried looking through the code, but as I'm not familiar with Android app development, I'm unsure where to find this information.

Any insights would be greatly appreciated. Thanks again for creating such a fantastic app!

**Comment by residuum** [comment]
The sampling rate is not settable by the app itself, but depending on the device. 

From the [official documentation](https://developer.android.com/develop/sensors-and-location/sensors/sensors_overview) (emphasis mine):

> The default data delay is suitable for monitoring typical screen orientation changes and uses a delay of 200,000 microseconds. You can specify other data delays, such as [SENSOR_DELAY_GAME](https://developer.android.com/reference/android/hardware/SensorManager#SENSOR_DELAY_GAME) (20,000 microsecond delay), [SENSOR_DELAY_UI](https://developer.android.com/reference/android/hardware/SensorManager#SENSOR_DELAY_UI) (60,000 microsecond delay), or [SENSOR_DELAY_FASTEST](https://developer.android.com/reference/android/hardware/SensorManager#SENSOR_DELAY_FASTEST) (0 microsecond delay). 

>**The delay that you specify is only a suggested delay. The Android system and other applications can alter this delay.** As a best practice, you should specify the largest delay that you can because the system typically uses a smaller delay than the one you specify (that is, you should choose the slowest sampling rate that still meets the needs of your application). Using a larger delay imposes a lower load on the processor and therefore uses less power.

>**There is no public method for determining the rate at which the sensor framework is sending sensor events to your application**[...]
